### PR TITLE
fix: const to let in "the <form> element"

### PR DESCRIPTION
**Pull request by golfomania**
**Lesson**
[The Form Element](https://learn.svelte.dev/tutorial/the-form-element)

**Problem**
In the load function in +page.server.js a new userid is created if not found in cookies
But id is declared as const so it can not be updated
Tutorial app run into 500 internal error

**How to reproduce**
e.g. open link in incognito window

**Fix**
change declaration from id from const to let

Martin
_This is my first open source contribution, so i hope this PR works for you this way_

### CODE REVIEW

**Comment by golfomania** [comment]
found more sections with the same code and changed it as well in second commit

**Comment by golfomania** [comment]
related to #543

**Comment by JonathanHarford** [comment]
I was just now working through the tutorial and bumped up against that problem. Thanks!

**Comment by golfomania** [comment]
@JonathanHarford as long as the PR is not accepted just fix it manually in the file 👍

**Comment by taylorgorman** [comment]
Came here to fix this, happy to see you beat me to it!

**Pull request merged**
