### PR TITLE
chore: reset selection color in editor

### LINKED ISSUE #279: The color of the selected text is white in editor
The color should not change.
In dark mode, it would be better to change the background color as well.

selection-text

### PR DESCRIPTION
**Pull request by tomoam**
Fixes #279

### CODE REVIEW

**Comment by Rich-Harris** [comment]
So much better, thank you!

**Comment by Rich-Harris** [comment]
(I notice the PR is still in draft, are you planning to fix dark mode in this PR as well?)

**Comment by tomoam** [comment]
> I notice the PR is still in draft, are you planning to fix dark mode in this PR as well?

I've done it. Sorry for the wait.

image

**Comment by Rich-Harris** [comment]
this looks fantastic, thanks so much!

**Pull request merged**
