### PR TITLE
styles update

### PR DESCRIPTION
**Pull request by dummdidumm**
Updates styles to closer match site-kit and adds support for dark mode.

This adds a temporary site-kit version (the same as in the current Kit repo), because there's no deployed version of the new site-kit yet. Once that's done, the temporary version should be removed and then we can merge this.

### CODE REVIEW

**Comment by Rich-Harris** [comment]
I think this is good to go, though I haven't merged it yet

**Comment by Rich-Harris** [comment]
found one thing that needs fixing

image

**Comment by geoffrich** [comment]
Another thing (maybe more obvious with dark mode?) - the bullets on a `<ul>` seem to have fixed position and stop lining up with the list items

image

**Comment by geoffrich** [comment]
Other things I noticed:

On [blog example](https://learn-svelte-hiy68qdgu-svelte.vercel.app/tutorial/params), link text is hard to read in dark mode
image


Also on the [error.html example](https://learn-svelte-hiy68qdgu-svelte.vercel.app/tutorial/fallback-errors)
image

And the [breaking out of layouts example](https://learn-svelte-hiy68qdgu-svelte.vercel.app/tutorial/breaking-out-of-layouts):
image

**Comment by jacob-8** [comment]
Can I request a dark/light mode toggle, please?

**Comment by dummdidumm** [comment]
I've gone through all the exercises and adjusted the colors so it looks both good/acceptable in light/dark mode. I also noticed a few things along the way, for which I'll open some issues. It mainly boils down to "Svelte core tutorial labels look shitty", "things are not loaded" and "alerts are broken".

**Pull request merged**
